plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "陈牧心"
email: adolph1998@163.com
description: ""
github:
  username: nsrfsn
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
  owner: NSRFSN
  repo: NSRFSN.github.io
  client_id: 8b90560b70334d45c7c5
  client_secret: 

url: "https://nsrfsn.github.io"
imgrepo: "https://nsrfsn.github.io/static/img"
